### ISSUE TITLE
Decreased Stamina Usage / Increased Stamina Regen

### ISSUE THREAD

**Issue by Gunnersmith** [MineInAbyss/server-config#103]
### Enchantment name

Endurance / Bounce-Back

### Enchantment Info

Endurance could use less stamina while using the climb mechanic within the server. There would simply just be 3 tiers, with each tier being 22% less usage of stamina, max being 66% (anymore and it feels broken, but any less would just deem it a useless enchantment.)

Bounce-back could be a different variant, where instead of less stamina usage, you have faster stamina regen, also up to 3 tiers, each +22%. This includes both when the player hits 0 stamina and can't climb, and when the player used some stamina and the bar is still green.

These enchantments can only be applied to the chestplate. 

### Obtainability

- [ ] Enchanted Books
- [ ] Enchantment Table (Randomly applied)
- [X] Vendor Trades
- [ ] Dungeon Loot
- [ ] Other (Details in Additional Info)

### Additional info

If the enchantment gets added, depending on how high the final percentages are set, it should also be worth mentioning that having access to both enchantments at tier 3 simultaneously could making climbing broken, so it's more of a caution.

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by Boy0000** [comment]
Staminatweaks would probably be done moreso through gear/tools/potions and perhaps pins rather than an enchantment on an item. 

Think BoTW Climbing Gear and so on
