### ISSUE TITLE
coal and charcoal to black dye in order to fill the gap

### ISSUE THREAD

**Issue by ronnor88** [MineInAbyss/server-config#143]
### Type

Shapeless

### Ingredients for the recipe

charcoal or coal 

### Result

black dye

### Additional info

flower villager will be added but the flower for black dye(whiter rose) wont be included so i feel like this would be a good fix

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by Naatchi** [comment]
i can work on this if you want @Boy0000
