### ISSUE TITLE
Make Plugin-checking check hash of file

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/server-config#168]
RN Using SNAPSHOT builds or plugins that dont specify a version in the jar-name means it just wont update the plugin
For example all our plugins, like MineInAbyss, are not updated even when a new SNAPSHOT build is published as the file is the "same"

**Comment by 0ffz** [comment]
Should effectively be fixed now that Keepup tracks the date header. Open an issue in Keepup if needs reopening.
