### ISSUE TITLE
Low spawn ratio of flying mobs

### ISSUE THREAD

**Issue by 24k-gold** [MineInAbyss/server-config#29]
not sure how github works but it seems total spawn number stays quiet same, the majority of mobs became ground/bug-kind and flying ones spawn so little that i haven't barely seen them while being at the lowest section of l3, almost 1 per a hour regardless of kind.

**Comment by 0ffz** [comment]
Flying bugs are considered flying mob types right now, in the future we will have more specific mob caps so they won't eat it up. As for the specific numbers, it's hard to say what they should be, but at least the bugs wont interfere with them.

**Comment by 24k-gold** [comment]
I think the mobs, those are given spawn condition with block-whitelist and not set priority, are overtaking the priority of other mobs, my guess, have priority below default value. Can we still give set priority for them while having whitelist? Or getting rid of priorites completely and giving them only max spawn amount?

**Comment by 0ffz** [comment]
Feel free to lower the priority of some of those mobs right now, though I think you're right and the best solution is to use default priority for almost everything so it just works™️. @Boy0000 thoughts?

**Comment by Boy0000** [comment]
yes and no. Just make a suggestion PR and ill see. Priority is kinda dumb aswell so i suppose

**Comment by Boy0000** [comment]
tried removing priority to see if it helps

**Comment by c-sig** [comment]
would changing creatureType to hostile be a temporary fix?

**Comment by Boy0000** [comment]
Don't think so, tried adding some to WATER_CREATURE and MONSTER, but it didnt improve it. Might try it on a larger scale soon
