### ISSUE TITLE
Nanachi's house, Mitty "bug"

### ISSUE THREAD

**Issue by TwigWallder** [MineInAbyss/server-config#47]
I don't know the bit of code create mitty (if you want to tell me, do it)

That's it in nanachi's house, mitty have big trouble, she is "physically" in the house there is the hitbox.
But there are no textures sometimes, I did some test and I don't understand where this bug comes from.
(I initially thought it was because of the shaders but it's not)

**Comment by Boy0000** [comment]
Not sure what server you mean, dont even think we have npcs spawned in.
Mitty's texture does in fact work so if you have the resourcepack then there shouldnt be any issues

**Comment by TwigWallder** [comment]
It's the survival server. and I have all the times the ressourcepack. it's true that it's not a big bug but I still want to report it
