### ISSUE TITLE
Railway nerf for new players (Minecart recipe change)

### ISSUE THREAD

**Issue by AATART** [MineInAbyss/server-config#69]
### Type

Shaped

### Ingredients for the recipe

A. Diamond
B. Iron block
C. Obsidian

### Result

Minecart

### Crafting table recipe shape

```bash
|   |
|B B|
|ACA|
```
### Comments

The goal of this recipe is to nerf railways and make em more expensive to use. This recipe will make em too expensive for new players and let them get their first gameplay experience without shortcuts.
Explanation:Abyss conditions is too harsh and better materials needed for minecart long usage 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by Boy0000** [comment]
The recipe doesnt really make sense and I think there are better options to make rails more viable. There will very quickly be community chests with minecarts in it.
