### ISSUE TITLE
Climbing Claws

### ISSUE THREAD

**Issue by skoinkus** [MineInAbyss/server-config#71]
### Type

Shaped

### Ingredients for the recipe

O: Orb Piercer Spikes
D: Diamonds
S: Stick

### Result

Climbing Claws; When you hold them in your hand/off-hand you lose stamina (25%?) slower while climbing walls.

### Crafting table recipe shape

```bash
| O |
|O O|
|DSD|
```

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by skoinkus** [comment]
I was also thinking that if you had two of them and you had one in both of your hands the effect would stack to 50%. This would increase your climbing capabilities in return for taking up both hands

**Comment by Boy0000** [comment]
Idea might work but the feature isnt available. When it is a thing there will be a recipe
