### ISSUE TITLE
Star Compass

### ISSUE THREAD

**Issue by skoinkus** [MineInAbyss/server-config#73]
### Type

Shaped

### Ingredients for the recipe

T: Titanjaw Pearl
I: Iron Ingots

### Result

Star Compass; A compass that points towards the center of the abyss

### Crafting table recipe shape

```bash
| I |
|ITI|
| I |
```

### Additional info

I saw some people asking where the center of the abyss was on the server and this came to mind. Just a compass recipe with a late game item instead of redstone. Also the pearl kind of looks like the compass from the show.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by AATART** [comment]
Guess there's recipe for star compass, but it temporary dosabled

**Comment by skoinkus** [comment]
Oh didn't know that, my bad
