### ISSUE TITLE
Nether Warts

### ISSUE THREAD

**Issue by skoinkus** [MineInAbyss/server-config#74]
### Where should this recipe be applied?

- [X] Furnace
- [ ] Blast Furnace
- [ ] Smoker
- [ ] Campfire

### Input Item

Hashofu Body

### Result

Nether Wart

### Additional info

Nether Warts are impossible to obtain unless you bum them off of other players (you can get orb piercer face fragments but they can't be planted for farming anymore ig) and hashofu bodies have no use outside of trading for orth coins i believe. Also they kind of look similar

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the recipe I'm requesting isn't already in the server.

**Comment by Boy0000** [comment]
What is the usecase for them tho? if its for brewing and stuff it would be better to skip the middle man and have them work as nether warts basically iguess

**Comment by skoinkus** [comment]
That could work, the only difference is hashofus can't be farmed automatically like warts

**Comment by Boy0000** [comment]
That's kind of the point. The moment you have one there is no need for new ones. And the entire drop becomes useless

**Comment by skoinkus** [comment]
Yeah that's true, having them work as nether warts directly would be better then
