### ISSUE TITLE
Prismarine Trader

### ISSUE THREAD

**Issue by xtremepipe** [MineInAbyss/server-config#80]
### Is your feature request related to a problem?

Is too hard to obtain a good amount of prismarine blocks at the moment

### Describe the solution you'd like.

Create a trader that sells all prismarine related blocks

### Describe alternatives you've considered.

Increase droprate/orespawn of prismarine materials

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
[Added](https://mineinabyss.notion.site/mineinabyss/Prismarine-Salesman-Paul-979955bfdd394da78c5c047c17eb994d)
