### ISSUE TITLE
Warped/Crimson Nylium Villager Trade

### ISSUE THREAD

**Issue by khaazz** [MineInAbyss/server-config#81]
### Is your feature request related to a problem?

I would like to be able to purchase some nylium

### Describe the solution you'd like.

Both types of nylium to be added to a villager trade

### Describe alternatives you've considered.

Possibly a crafting recipe for both nylium types, for example 1 netherack = 1 nylium or even 4:1

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
Perhaps you could suggest trade prices, name of the villager, location, should it be a brand new one, or added to a previous one etc

**Comment by Boy0000** [comment]
Added to **Norah, The Warped**
