### ISSUE TITLE
Remove potion particles for the curse

### ISSUE THREAD

**Issue by xtremepipe** [MineInAbyss/server-config#82]
### Is your feature request related to a problem?

The curse is something happening inside your body, so shouldn't exist a feedback with potion particles.

### Describe the solution you'd like.

Remove potion particle for curse effects.

### Describe alternatives you've considered.

No other alternatives, or keep it as it is.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by xtremepipe** [comment]
except for vomiting and bleeding effect

**Comment by Boy0000** [comment]
Curse rework will be done eventually which prob means this might happen. Might be doable in the mineinabyss part of the config already, so feel free to make a PR for that. Otherwise it will come then 👍
