### ISSUE TITLE
Thorns III and Silk Touch Villager Trade

### ISSUE THREAD

**Issue by Kaysuami** [MineInAbyss/server-config#83]
### Is your feature request related to a problem?

These enchantments are rare in the enchanting table especially for Thorns III and there is a empty shop spot among the villagers enchantment shops.

### Describe the solution you'd like.

Both Thorns III and Silk Touch to be added to Villager Trades in Orth. The prices for Silk Touch would be 12 Orth coins and Thorns III would be 14 Orth coins.

### Describe alternatives you've considered.

By making them more common in the enchanting table list or create new type of enchantment table that does not give only three enchantments.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
Tweaking ETable is planned. If you want it as a villager, suggest a location, prices, villager name and all that iguess

**Comment by Kaysuami** [comment]
Then the villager would be named Jag, location would be at 512,126,-172 at Orth. Prices for Thorns III would be 13 Orth coins and Silk Touch would be 12 Orth coins.

**Comment by Boy0000** [comment]
[Added](https://mineinabyss.notion.site/mineinabyss/15cb6f2412904e398bc57d7162a59bcc?v=42a06df67ac6416486e49d198b288d7d&p=6ba014f8238046f1b3142539536a90b5)
