### ISSUE TITLE
More coral

### ISSUE THREAD

**Issue by pandawanda223** [MineInAbyss/server-config#84]
### Is your feature request related to a problem?

yes, farming coral takes way too long

### Describe the solution you'd like.

being able to buy coral from villagers, I would suggest being able to buy tube, brain, bubble, fire, and horn coral, leaving the blocks as something u can only get from farming ashmite. I would say making all the corals 1 orth coin for 1 coral of each type, and naming the villager coral smuggler Anthony, and putting the villager inside of the slum market near the fishe trader

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

:yeeko:

**Comment by Boy0000** [comment]
Perhaps you could suggest trade prices, types of coral, should blocks/fans/coral be there or only parts, name of the villager, location etc.

**Comment by pandawanda223** [comment]
I would suggest being able to **buy tube, brain, bubble, fire, and horn coral,** leaving the blocks as something u can only get from farming ashmite. I would say making **all the corals 1 orth coin for 1 coral of each type,** and naming the villager **coral smuggler Anthony**, and putting the villager inside of the **slum market near the fishe trader**

**Comment by Boy0000** [comment]
Added to **Ocean Fanatic Frank**
