### ISSUE TITLE
Reintroduce Ambient Lighting

### ISSUE THREAD

**Issue by caramelliaa** [MineInAbyss/server-config#85]
### Is your feature request related to a problem?

i agree with the fact that the abyss shouldnt be perfectly lit, but lighting right now is really hard to play with. at default lighting i can't see a thing at all in goblets, which is a weird way to add artificial difficulty. From what i've seen, a lot of players on the server agree that it's too dark by default too. imo the previous level of lighting from a week (?) ago was perfect for the abyss, dark enough that its difficult to make some things out but not dark enough that its literal complete blackness if nobody spams torches on the ground like a madman, and also makes some great player made builds super hard to see

### Describe the solution you'd like.

Reintroduce the ambient lighting that was in the game until it got removed recently, i'm not sure if it was 0.4 or 0.5? 

### Describe alternatives you've considered.

from what im aware most players that spend time in the lower layers 4 or 5 manually turn their gamma up. i think it's weird and unintuitive for newer players that people would need to do this by themselves when it was fine before. Plus it's not a change to be super opposed to if everyone's finding their own ways around it anyway, just thinking for the newer players here mainly

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
The way it is now is vanilla, and is what it has been like for the past 4 years more or less. I've not heard any feedback on it except from 2-3 people. It makes it easier to tell when mobs should/shouldnt be able to spawn for light connditions. Makes it not just bright in spots it makes no sense to.

Gear and equipment to generate light is planned, for now if you cant stand it. Fullbright is allowed, and if you havent, up your brightness. Or just get some dynamic light mods.
