### ISSUE TITLE
Beacon :yeeko:

### ISSUE THREAD

**Issue by pandawanda223** [MineInAbyss/server-config#87]
### Item Type

Other

### Item name

Beacon

### Item Info

What usually a beacon does

### Item Model/Texture

normal beacon

### Obtainability

craftable

### Related recipe ideas

#86

### Additional info

combining a rare mineral with mob drops
my suggestion would be to make a mithril block as a base, make a base of makihage obsidian and adamantite so either x-x
adamantite being the x and makihage obsidian the -. then for the "netherstar" something along the lines of combined Rohana  tails with orb piercer spikes and a titanjaw pearl to make triangle thingies, combining these triangle thingies with something along the lines of quartz surrounding a adamantite block and then to finish u just surround the empty spots with glass

so to make stuff easier and more complicated at the same time I am gonna assign each item a symbol/number to show how it should be crafted or be used to craft something
keep note that 0 means empty space

mithril block = #
obsidian alloy = &
(makihage obsidian) = 1
(adamantite) =2
000
000
212
star fragments = >
(rohanatails) = 3
(orbpiercer spikes) =4
(titanjaw pearl) = 5
434
353
434
star core = +
(quartz) =6
(adamantite block) = 7
666
676
666
to make a nether star you would do the following
0>0
>+>
0>0
nether star is in symbol *
glass is just g cuzz I am lazy
ggg
g*g
&#&

This is a shitty draft that can be improved on my end, but pls tell me what you don't understand because I know u will not understand something about this, and I agree it is explained poorly, also elaborate what u dislike about it because I know u will say something like that

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the relic I'm suggesting isn't already on the server.

**Comment by Boy0000** [comment]
Make the recipe link to an actual recipe suggestion, dont put it in additional info
