### ISSUE TITLE
Lights Villager Trade

### ISSUE THREAD

**Issue by Kaysuami** [MineInAbyss/server-config#90]
### Is your feature request related to a problem?

Soul sand are hard to get when mining, need lots of soul lantern my future build.

### Describe the solution you'd like.

A villager trader that sells lantern, soul lantern, sea lantern and glowstone. 1 Orth coin for 16 lanterns, 2 Orth Coins for Soul Lantern and the rest are 4 Orth coins for 16.

### Describe alternatives you've considered.

Increase the rate of droprate of soul sand

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
This shouldn't be an issue as [Nereth](https://www.notion.so/mineinabyss/15cb6f2412904e398bc57d7162a59bcc?v=42a06df67ac6416486e49d198b288d7d&p=d6754f6605b44eb49208eec142c44a25) sells soul sand and soil
