### ISSUE TITLE
Splitjaw/Orby Tweaks

### ISSUE THREAD

**Issue by caramelliaa** [MineInAbyss/server-config#91]
### Is your feature request related to a problem?

I haven't really seen anyone else discussing this stuff so this is just largely my own personal opinion, I can't speak for the rest of the server but i don't think these changes would be controversial hopefully.

1) I didn't personally have this problem when I started out but imo splitjaws are just a bit too troublesome for newer players, and it's really common to see newer players getting massacred over and over again by splitjaws in layer 1/2. The wiki also says 'it is exceedingly rare to see them in the most shallow sections of the Abyss.' 

2) Orbpiercers are way too rare, you've probably seen me or other people complaining about this but I think they're too uncommon rn even after their criteria is met. As of rn there hasn't been a new orbpiercer caused death in 24 hours which I can only assume means there've been virtually no spawns for the past day. While I get that they're canonically rare, for such an iconic mob i think it's weird how 99% of new players won't find one on their journey through L4. I also think they should be easier to find for players actively trying to seek them out. It's the survival server after all, PvE is some people's favourite endgame.

### Describe the solution you'd like.

1) I think splitjaws should be just a bit less common in layer 1. Possibly decrease the spawn priority in layer 1 slightly? It's a bit strange for them to be more common in edge of abyss than 3 which is their canon living area. By layer 2/3 players should have gotten the hang of the gameplay so their rarity is fine there 

2) I didnt see anything about orbies being nocturnal on the wiki but I don't really have an issue with that being in the game. For the other spawn conditions, if im not mistaken, priority was 0.5 and spawndelay was 5s before the big change to the spawn table a week ago. That's probably too high, so maybe it could be changed to priority 0.2 or 0.25 + spawndelay 5s? To my knowledge, the only use for orby spikes rn is 7 per orth coin, maybe that could be tweaked to 9 or 10 if necessary to balance it out. And if orby faces for backpacks is a concern, drop rate of orby faces could be halved. 

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

I think the main concern about orbies being more common rn is them being farmed. Honestly though, I dont think farming orbies for coins should be something to be actively discouraged by the server considering how dangerous they are in comparison to other coin methods like just passive makihige and great fault flying mob hunting. And if the backpacks are a concern then the recipe could either be made harder with 2 faces instead of 1 or the face drop rates should go down, though I doubt anyone is mass hunting orbies for backpacks when they're available for 10 orth. Plus, I don't think anyone was living off orby-based income even when the rates were as high as they were a week ago, so I really don't think this will cause any unfair shift in the economy.

**Comment by Boy0000** [comment]
You can always make an actual SpawnConfig suggestion change by following [this](https://mineinabyss.com/config)
Testing it is very annoying as it requires it to be on survival and a full restart for any little change though so

**Comment by caramelliaa** [comment]
Ahh i didnt know there was an actual page for it thanks! i'll follow that! probably good that i included the reasoning here though so you can see x)
